### ISSUE TITLE
Installing the ISO to a USB drive

### ISSUE THREAD

**Issue by Preisschild** [tfc/nixos-offline-installer-experiment#3]
Hi, complete Nix newbie here.

I've executed `nix-build installer-iso.nix` and generated a iso
`result/iso/nixos-offline-installer-20.09pre237686.96069f7d890-x86_64-linux.iso: ISO 9660 CD-ROM filesystem data (DOS/MBR boot sector) 'NIXOS_ISO' (bootable)`.

For some reason, I cant install it to an usb drive with dd though:
```
sudo dd if=result/iso/nixos-offline-installer-20.09pre237686.96069f7d890-x86_64-linux.iso of=/dev/sdf
dd: writing to '/dev/sdf': No space left on device
1641641+0 records in
1641640+0 records out
840519680 bytes (841 MB, 802 MiB) copied, 0.971187 s, 865 MB/s
``` 

the ISO has a size of 3.5G, and the usb drive 32G. Installing other isos works fine the same way.

Can you help me there?

**Comment by tfc** [comment]
That looks odd. Can you post what `fdisk -l /dev/sdf` says? Maybe the system has a different opinion about the stick's size and thus does not want to exceed that.

**Comment by Preisschild** [comment]
Thanks for replying!

Yea you were right. For some reason /dev/sdf reported only ~500mb storage but /dev/sdf1 reported the full 32gb size.

Restarting fixed this issue

/close
